//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 05:23:09 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/clinic/schemas/patient")
package edu.stevens.cs548.clinic.service.dto.patient;
